services:
  - type: web
    name: gmail-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: EMAIL
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
